Sample collection
PIH/openmrs-config-ses pull request #26
Opened 2021-06-22 23:23 UTC by MiguelAHPpih

National document configurations

2021-06-23 16:49 UTC, brandones commented on configuration/concepts/seslab.csv:Zone.Identifier
> +[ZoneTransfer]
Esto tiene que ver con alguna herramienta que estas usando para gestionar este archivo?

2021-06-23 16:55 UTC, MiguelAHPpih commented on configuration/concepts/seslab.csv:Zone.Identifier
> +[ZoneTransfer]
Mmm no creo, cuando hice el commit no figuraba ese archivo.

2021-06-23 16:56 UTC, brandones commented on configuration/pih/htmlforms/sampleCollection.xml
> +            </td>
`render` is only valid within the `repeat` tag. You probably want something very similar to the example shown in the docs: https://wiki.openmrs.org/display/docs/HTML+Form+Entry+Module+Reference#HTMLFormEntryModuleReference-%3Crender%3E

2021-06-23 16:58 UTC, brandones commented on configuration/pih/scripts/global/sampleCollection.js
> +	  const encounterId = urlParams.get("encounterId"), patientId = urlParams.get("patientId");
```suggestion
	  const encounterId = urlParams.get("encounterId");
	  const patientId = urlParams.get("patientId");
```

The comma operator should generally be avoided.

2021-06-23 17:00 UTC, brandones commented on configuration/pih/scripts/global/sampleCollection.js
> +	  let fechaVisitaValue=new Date(Date.parse(encounter.encounterDatetime)).toLocaleString();
```suggestion
	  const fechaVisitaValue = new Date(Date.parse(encounter.encounterDatetime)).toLocaleString();
```

2021-06-23 17:00 UTC, brandones commented on configuration/pih/scripts/global/sampleCollection.js
> +	  let examenes=[];
```suggestion
	  const examenes = [];
```

2021-06-23 17:02 UTC, brandones commented on configuration/pih/scripts/global/sampleCollection.js
> +	  $.each(encounter.orders, (i, orders) => {
jQuery is fortunately no longer necessary for these constructs:

```suggestion
	  encounter.orders.forEach((i, orders) => {
```

2021-06-23 17:04 UTC, brandones commented on configuration/pih/scripts/global/sampleCollection.js
> +	  $.each(encounter.orders, (i, orders) => {
You could also have done

```js
const examenes = encounter.orders.map(o => o.display);
examenes.forEach(e => $("#examenes").append($(`<td>${e}</td>`)));
```

2021-06-23 17:05 UTC, brandones commented on configuration/pih/scripts/global/sampleCollection.js
> +	  const paciente= await $.get(`/openmrs/ws/rest/v1/patient/${patientId}`);
Please put spaces around assignment operators.

```suggestion
	  const paciente = await $.get(`/openmrs/ws/rest/v1/patient/${patientId}`);
```

2021-06-23 17:08 UTC, brandones commented on configuration/pih/scripts/global/sampleCollection.js
> +	  let apeMaternoValue=paciente.person.display.split(" ")[0];
I expect that the `paciente` object has a `names` array that you could more safely get this information from. You should make sure this code is robust to patients having incomplete or poorly formatted names. It should not crash when the patient has the wrong number of names.

2021-06-23 17:09 UTC, brandones commented on configuration/pih/scripts/global/sampleCollection.js
> +	  let fecnac=new Date(Date.parse(paciente.person.birthdate)).toLocaleDateString('en-ZA');
`en-ZA`? South Africa???

2021-06-23 17:11 UTC, brandones commented on configuration/pih/scripts/global/sampleCollection.js
> +	  let fechaNacimientoValue=fecnac.substring(0,10);
You shouldn't need to do this. Just pass the right parameters to `toLocaleDateString`: https://stackoverflow.com/a/34015511/1464495

2021-06-23 17:14 UTC, brandones commented on configuration/pih/scripts/global/sampleCollection.js
> +	  $.each(paciente.identifiers, (i=1, data) => {
```suggestion
	  paciente.identifiers.forEach(data => {
```

2021-06-23 17:14 UTC, brandones commented on configuration/pih/scripts/global/sampleCollection.js
> +		  console.log(data);
```suggestion
		  //console.log(data);
```

2021-06-23 17:16 UTC, brandones requested changes
Unos sugerencias y preguntas del JavaScript

2021-06-23 19:00 UTC, mogoodrich reviewed
Thanks @MiguelAHPpih  ... I made a few comments, and also pushed up a couple proposed changes to the identifier configuration.  I made comments where I made the changes, let me know if it looks good to you!

fyi @brandones

2021-06-23 19:00 UTC, mogoodrich commented on configuration/pih/pih-config-peru.json
> +  "findPatientColumnConfig": [
I made a couple changes here, see below... instead of a "type of identifier" column and a "identifier" column, this renders a separate column for DNI and Passport (feel free to adjust the labels as you see fit).

I believe this isn't exactly what you wanted, but it seemed good to do this as a start as we work through potential changes to the Core Apps module.

2021-06-23 19:00 UTC, mogoodrich commented on configuration/pih/pih-config-peru.json
> +  "findPatientColumnConfig": [
![2021-06-23_14-49](https://user-images.githubusercontent.com/1163015/123153205-6a7e1300-d433-11eb-8b4e-2fa2b9236a65.png)

2021-06-23 19:00 UTC, mogoodrich commented on configuration/pih/pih-config-peru.json
> +    "${patientIdentifierType.Passport.uuid}"
These two lines add the DNI and Passport to the patient header (and make them editable via the header).  Not sure if that's what you want, but I wanted to add it in as a example.

2021-06-23 19:00 UTC, mogoodrich commented on configuration/pih/pih-config-peru.json
> +    "${patientIdentifierType.Passport.uuid}"
![2021-06-23_14-49_1](https://user-images.githubusercontent.com/1163015/123153337-8d102c00-d433-11eb-9bba-df43830428a6.png)

2021-06-24 15:26 UTC, MiguelAHPpih commented on configuration/concepts/seslab.csv:Zone.Identifier
> +[ZoneTransfer]
To be honest I don't remember having committed this file, i even didn't see it when i typed git status. Should be okay if we ignore it

2021-06-24 15:38 UTC, MiguelAHPpih commented on configuration/concepts/seslab.csv
> +uuid,Void/Retire,Same as mappings,Fully specified name:es,Fully specified name:en,Data class,Data type,_version:1,_order:1000
I think this is because they already exist on the concept server, but since this csv was made for only Perú i decided to leave it like that and fix it on the future

2021-06-24 15:54 UTC, brandones commented on configuration/concepts/seslab.csv:Zone.Identifier
> +[ZoneTransfer]
You can `git rm --cached [filename]` to remove something from version control

2021-06-24 16:13 UTC, MiguelAHPpih commented on configuration/pih/pih-config-peru.json
> +  "findPatientColumnConfig": [
This could be a nice workaround. But i think in the future we might add more document types, therefore having more columns.

2021-06-24 16:22 UTC, MiguelAHPpih commented on configuration/concepts/seslab.csv:Zone.Identifier
> +[ZoneTransfer]
Okay, i think this is something that is generated after the concepts are loaded for the first time. It's only a guess, not 100% sure

2021-06-24 19:15 UTC, mogoodrich commented on configuration/pih/pih-config-peru.json
> +  "findPatientColumnConfig": [
Cool, yeah, makes sense @MiguelAHPpih  see my updated comments on the coreapps pull request about moving forward with supporting multiple identifiers per column:

https://github.com/openmrs/openmrs-module-coreapps/pull/414

2021-06-24 19:24 UTC, mogoodrich commented on configuration/concepts/seslab.csv
> +uuid,Void/Retire,Same as mappings,Fully specified name:es,Fully specified name:en,Data class,Data type,_version:1,_order:1000
I'm not sure if it's because of the concept server... I tried to run it on my local SES dev environment and got the error... and unfortunately we changed how things work now so that startup fails entirely if something can't be installed.

I'm trying rerunning again now because it looks like the above message I pasted doesn't include the underlying error.

2021-07-14 22:53 UTC, MiguelAHPpih commented on configuration/pih/htmlforms/sampleCollection.xml
> +            </td>
When I apply the `repeat` tag and then `template,` it disables the id tag. Is that normal?

2021-07-14 23:24 UTC, brandones commented on configuration/pih/htmlforms/sampleCollection.xml
> +            </td>
I don't know why you're using the `repeat`/`render`/`template` tag family at all. Those are for when you want to repeat something; e.g. if you had multiple rows you wanted to display. I think you just have the one row.

What is the row supposed to show? Input boxes (use `obs`)? Or display data from Velocity (use `lookup`)? Or are they populated by JavaScript (use normal `div` with `id`)?

2021-07-15 14:56 UTC, MiguelAHPpih commented on configuration/pih/htmlforms/sampleCollection.xml
> +            </td>
It's more like a label were a text should appear. All of them are populated via JavaScript using `id`'s

2021-07-15 15:51 UTC, brandones commented on configuration/pih/htmlforms/sampleCollection.xml
> +            </td>
Okay, well if it's populated via Javascript then you can just do

```html
<div id="proyecto"></div>
```

etc.

2021-07-15 19:42 UTC, MiguelAHPpih commented on configuration/concepts/seslab.csv
> +uuid,Void/Retire,Same as mappings,Fully specified name:es,Fully specified name:en,Data class,Data type,_version:1,_order:1000
@mogoodrich , did you have any troubles with this again?

2021-07-15 19:44 UTC, MiguelAHPpih commented on configuration/pih/pih-config-peru.json
> +  "findPatientColumnConfig": [
I'm ok with this, until we get the coreapps function. Mergin it!

2021-07-15 21:56 UTC, brandones commented on configuration/pih/htmlforms/sampleCollection.xml
> +            <render map="PIH:2485" id="examenes"/>
Same with this one

2021-07-15 21:56 UTC, brandones commented on configuration/pih/htmlforms/sampleCollection.xml
> +            <render map="PIH:2485" id="examenes"/>
```suggestion
            <div id="examenes"></div>
```

2021-07-19 18:03 UTC, MiguelAHPpih commented
I think we can merge this now. ¿Any thoughts?

2021-07-19 20:56 UTC, mogoodrich commented
@brandones  @MiguelAHPpih  did you want me to test this again?

2021-07-19 22:08 UTC, MiguelAHPpih commented
@mogoodrich Yes, please.

2021-07-19 22:18 UTC, mogoodrich commented
@MiguelAHPpih will do!  won't get to it today, but hopefully tomorrow!

2021-07-20 16:30 UTC, mogoodrich commented
@brandones  @MiguelAHPpih  not sure if I'm working off the branch or something, but I'm still getting a bunch of duplicate concept name exceptions:

+--------------------------------------+-------------+-----------------------+-------------------------+-------------------------+------------+-----------+------------+-------------+
| uuid                                 | Void/Retire | Same as mappings      | Fully specified name:es | Fully specified name:en | Data class | Data type | _version:1 | _order:1000 |
+--------------------------------------+-------------+-----------------------+-------------------------+-------------------------+------------+-----------+------------+-------------+
| 0b6f8714-6cd5-4da7-b89b-5649d6855259 |             | SES Lab:SAMPLE_Plasma |                  Plasma |                  Plasma |   Specimen |       N/A |            |             |
+--------------------------------------+-------------+-----------------------+-------------------------+-------------------------+------------+-----------+------------+-------------+
org.openmrs.api.DuplicateConceptNameException: 'Plasma' is a duplicate name in locale 'en'
	at org.openmrs.validator.ConceptValidator.validate(ConceptValidator.java:177)
	at org.openmrs.api.db.hibernate.HibernateAdministrationDAO.validate(HibernateAdministrationDAO.java:262)
	at org.openmrs.api.impl.AdministrationServiceImpl.validate(AdministrationServiceImpl.java:800)
	at sun.reflect.GeneratedMethodAccessor149.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy201.validate(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor149.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.cache.interceptor.CacheInterceptor$1.invoke(CacheInterceptor.java:52)
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:303)
	at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:61)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.openmrs.aop.LoggingAdvice.invoke(LoggingAdvice.java:122)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:52)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:52)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy203.validate(Unknown Source)
	at org.openmrs.validator.ValidateUtil.validate(ValidateUtil.java:67)
	at org.openmrs.aop.RequiredDataAdvice.before(RequiredDataAdvice.java:127)
	at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:51)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:52)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy200.saveConcept(Unknown Source)
	at org.openmrs.module.initializer.api.c.ConceptsCsvParser.save(ConceptsCsvParser.java:93)
	at org.openmrs.module.initializer.api.c.ConceptsCsvParser.save(ConceptsCsvParser.java:17)
	at org.openmrs.module.initializer.api.CsvParser.process(CsvParser.java:199)
	at org.openmrs.module.initializer.api.loaders.BaseCsvLoader.load(BaseCsvLoader.java:69)
	at org.openmrs.module.initializer.api.loaders.BaseInputStreamLoader.load(BaseInputStreamLoader.java:39)
	at org.openmrs.module.initializer.api.loaders.BaseFileLoader.loadUnsafe(BaseFileLoader.java:42)
	at org.openmrs.module.pihcore.setup.InitializerSetup.loadPreConceptDomains(InitializerSetup.java:45)
	at org.openmrs.module.pihcore.PihCoreActivator.started(PihCoreActivator.java:97)
	at org.openmrs.module.ModuleUtil.refreshApplicationContext(ModuleUtil.java:928)
	at org.openmrs.module.web.WebModuleUtil.refreshWAC(WebModuleUtil.java:853)
	at org.openmrs.web.Listener.performWebStartOfModules(Listener.java:632)
	at org.openmrs.web.Listener.performWebStartOfModules(Listener.java:612)
	at org.openmrs.web.Listener.startOpenmrs(Listener.java:251)
	at org.openmrs.web.WebDaemon$1.run(WebDaemon.java:42)
WARN - BaseCsvLoader.lambda$load$0(87) |2021-07-20 11:04:50,774| An OpenMRS object could not be constructed or saved from the following CSV line:
+--------------------------------------+-------------+----------------------------+-------------------------+-------------------------+------------+-----------+------------+-------------+
| uuid                                 | Void/Retire | Same as mappings           | Fully specified name:es | Fully specified name:en | Data class | Data type | _version:1 | _order:1000 |
+--------------------------------------+-------------+----------------------------+-------------------------+-------------------------+------------+-----------+------------+-------------+
| 27b9eb31-6c54-4079-8079-c5ddc133fe75 |             | SES Lab:SAMPLE_Whole blood |            Sangre Total |             Whole blood |   Specimen |       N/A |            |             |
+--------------------------------------+-------------+----------------------------+-------------------------+-------------------------+------------+-----------+------------+-------------+
org.openmrs.api.DuplicateConceptNameException: 'Whole blood' is a duplicate name in locale 'en'
	at org.openmrs.validator.ConceptValidator.validate(ConceptValidator.java:177)
	at org.openmrs.api.db.hibernate.HibernateAdministrationDAO.validate(HibernateAdministrationDAO.java:262)
	at org.openmrs.api.impl.AdministrationServiceImpl.validate(AdministrationServiceImpl.java:800)
	at sun.reflect.GeneratedMethodAccessor149.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springfram [...]

2021-07-20 17:45 UTC, brandones commented
Maybe we can remove `concepts/seslab.csv` from this branch and merge it in, and then deal with the concepts separately? @MiguelAHPpih

2021-07-20 17:54 UTC, MiguelAHPpih commented
@brandones Yeah,that's better.

2021-07-20 18:03 UTC, brandones approved these changes

2021-07-20 18:04 UTC, merged